COMPANY_LOGOS = {
  'Cube': 'cube.jpeg',
  'Shutterfly': 'shutterfly.jpeg',
  'Meta': 'meta.jpeg',
  'Wolters Kluwer': 'wolters.jpeg',
  'Wipro': 'wipro.jpeg',
  'Autodesk': 'autodesk.jpeg',
  'Cognizant': 'cognizant.jpeg',
  'TriNet': 'trinet.jpeg',
  'LegalZoom': 'legalzoom.jpeg',
  'Mphasis': 'mphasis.jpeg',
  'John Deere': 'deere.jpeg',
  'Infogain': 'infogain.jpeg',
  'ServiceNow': 'servicenow.jpeg',
  'Indiana University': 'idu.jpeg',
  'Urgent IT Solutions': 'urgentit.jpeg',
  'American Society of Clinical Oncology': 'asco.jpeg',
  'Walmart': 'walmart.jpeg',
  'United Health Group': 'unitedhealthgroup.jpeg',
  'United Airlines': 'unitedairlines.jpeg',
  'Mursion': 'mursion.jpeg',
  'Adobe': 'adobe.jpeg',
  'CVS Health': 'cvshealth.jpeg',

  'National University of Singapore': 'nus.jpeg',
  'Curtin University': 'cu.jpeg',
  'Hong Kong University of Science and Technology': 'hku.jpeg',
  'Nanyang Technological University': 'ntu.jpeg',
  'Florida International University': 'fiu.jpeg',
  'Penn State University': 'penn.jpeg',
  'Georgia Southwestern State University': 'gss.jpeg',
  'Florida Southwestern State College': 'fssc.jpeg',
}